Validator CASNumberCheckDigit for Chemical Registry CAS Numbers and ECNumberCheckDigit
apache/commons-validator pull request #216
Opened 2024-05-04 14:01 UTC by homebeaver

CASNumberCheckDigit - CAS Chemical Abstracts Service RN Registry No

CAS Numbers are unique identification numbers used to identify chemical
substance described in the open scientific literature.

see [wikipedia CAS_Registry_Number](https://en.wikipedia.org/wiki/CAS_Registry_Number)

Also add Validator for EC number - ECN is a unique seven-digit identifier that is assigned to chemical substances

regards

2024-05-04 21:41 UTC, garydgregory requested changes
Hello @homebeaver 
Thank you for your PR.
Please see my comments.

2024-05-04 21:41 UTC, garydgregory commented on src/main/java/org/apache/commons/validator/routines/checkdigit/CASNumberCheckDigit.java
> + *
This comment is missing paragraph elements.

2024-05-04 21:41 UTC, garydgregory commented on src/main/java/org/apache/commons/validator/routines/checkdigit/CASNumberCheckDigit.java
> +    public static final CheckDigit CAS_CHECK_DIGIT = new CASNumberCheckDigit();
Use `INSTANCE` for the singleton name, make it private and add a `getInstance()` public static method (like `DoubleValidator.getInstance()` and friends.)

2024-05-04 21:41 UTC, garydgregory commented on src/main/java/org/apache/commons/validator/routines/checkdigit/CASNumberCheckDigit.java
> +    public CASNumberCheckDigit() {
This can probably be private.

2024-05-04 21:41 UTC, garydgregory commented on src/main/java/org/apache/commons/validator/routines/checkdigit/ECNumberCheckDigit.java
> + * <p>
Unbalanced HTML tag.

2024-05-04 21:41 UTC, garydgregory commented on src/main/java/org/apache/commons/validator/routines/checkdigit/ECNumberCheckDigit.java
> +        return (leftPos >= EC_LEN) ? 0 : charValue * leftPos;
Parens are not needed.

2024-05-04 21:41 UTC, garydgregory commented on src/test/java/org/apache/commons/validator/routines/checkdigit/AbstractCheckDigitTest.java
> +                if(codeWithNoCheckDigit==null) {
1. Use spaces around '=='.
2. Rebase on git master to pick up a Checkstyle rule that will check for this.
3. Run `mvn` by itself to check

2024-05-04 21:41 UTC, garydgregory commented on src/test/java/org/apache/commons/validator/routines/checkdigit/CASNumberCheckDigitTest.java
> + * CAS Number Check Digit Test.
Replace with `Tests {@link CASNumberCheckDigit}.`

2024-05-05 09:30 UTC, homebeaver commented
> ... see my comments.

Tkx for hints @garydgregory - Changes done - regards

2024-05-05 15:12 UTC, garydgregory requested changes
Hello @homebeaver 
- Thank you for updating this pull request.
- Please rebase on git master and see my comments.
- Checkstyle issues have been fixed in tests in git master.
- See my comments in this PR.
- Make sure you rebase on git master and run `mvn` by itself to run the default Maven goal

2024-05-06 11:02 UTC, closed without merging